language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm
    - nightly

# run build against nightly but allow them to fail
matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: nightly

# faster builds on new travis setup not using sudo
sudo: false

services:
    - memcached

# cache vendor dirs
cache:
    directories:
        - lib/vendor
        - $HOME/.composer/cache

install:
    - composer self-update

before_script:
    - composer install

script:
    - vendor/bin/phpunit -c phpunit.xml
